Added quiet, changed --gz to --compress

diff --git a/database-backup b/database-backup
--- a/database-backup
+++ b/database-backup
@@ -1,13 +1,14 @@
 #!/bin/bash
 #
 #
-# ARG_OPTIONAL_SINGLE([username],[],[Database username])
-# ARG_OPTIONAL_SINGLE([password],[],[Database password])
-# ARG_OPTIONAL_SINGLE([host],[],[Database host],[localhost])
-# ARG_OPTIONAL_SINGLE([port],[],[Database port],[3306])
-# ARG_OPTIONAL_SINGLE([output-directory],[],[Output directory],[/tmp])
-# ARG_OPTIONAL_BOOLEAN([gz],[],[Directly gzip output])
-# ARG_OPTIONAL_REPEATED([ignore],[],[Ignore table in export],['information_schema' 'innodb' 'performance_schema' 'tmp' 'mysql' 'sys'])
+# ARG_OPTIONAL_SINGLE([username],[u],[Database username])
+# ARG_OPTIONAL_SINGLE([password],[p],[Database password])
+# ARG_OPTIONAL_SINGLE([host],[H],[Database host],[localhost])
+# ARG_OPTIONAL_SINGLE([port],[P],[Database port],[3306])
+# ARG_OPTIONAL_SINGLE([output-directory],[o],[Output directory],[/tmp])
+# ARG_OPTIONAL_BOOLEAN([compress],[c],[Directly compress (gzip) output])
+# ARG_OPTIONAL_BOOLEAN([quiet],[q],[Directly gzip output])
+# ARG_OPTIONAL_REPEATED([ignore],[i],[Ignore table in export],['information_schema' 'innodb' 'performance_schema' 'tmp' 'mysql' 'sys'])
 # ARG_HELP([database-backup])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
@@ -28,7 +29,7 @@ die()
 begins_with_short_option()
 {
 	local first_option all_short_options
-	all_short_options='h'
+	all_short_options='upHPocqih'
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -41,20 +42,22 @@ _arg_password=
 _arg_host="localhost"
 _arg_port="3306"
 _arg_output_directory="/tmp"
-_arg_gz="off"
+_arg_compress="off"
+_arg_quiet="off"
 _arg_ignore=('information_schema' 'innodb' 'performance_schema' 'tmp' 'mysql' 'sys')
 
 print_help ()
 {
 	printf '%s\n' "database-backup"
-	printf 'Usage: %s [--username <arg>] [--password <arg>] [--host <arg>] [--port <arg>] [--output-directory <arg>] [--(no-)gz] [--ignore <arg>] [-h|--help]\n' "$0"
-	printf '\t%s\n' "--username: Database username (no default)"
-	printf '\t%s\n' "--password: Database password (no default)"
-	printf '\t%s\n' "--host: Database host (default: 'localhost')"
-	printf '\t%s\n' "--port: Database port (default: '3306')"
-	printf '\t%s\n' "--output-directory: Output directory (default: '/tmp')"
-	printf '\t%s\n' "--gz,--no-gz: Directly gzip output (off by default)"
-	printf '\t%s\n' "--ignore: Ignore table in export (default array: ('information_schema' 'innodb' 'performance_schema' 'tmp' 'mysql' 'sys') )"
+	printf 'Usage: %s [-u|--username <arg>] [-p|--password <arg>] [-H|--host <arg>] [-P|--port <arg>] [-o|--output-directory <arg>] [-c|--(no-)compress] [-q|--(no-)quiet] [-i|--ignore <arg>] [-h|--help]\n' "$0"
+	printf '\t%s\n' "-u,--username: Database username (no default)"
+	printf '\t%s\n' "-p,--password: Database password (no default)"
+	printf '\t%s\n' "-H,--host: Database host (default: 'localhost')"
+	printf '\t%s\n' "-P,--port: Database port (default: '3306')"
+	printf '\t%s\n' "-o,--output-directory: Output directory (default: '/tmp')"
+	printf '\t%s\n' "-c,--compress,--no-compress: Directly compress (gzip) output (off by default)"
+	printf '\t%s\n' "-q,--quiet,--no-quiet: Directly gzip output (off by default)"
+	printf '\t%s\n' "-i,--ignore: Ignore table in export (default array: ('information_schema' 'innodb' 'performance_schema' 'tmp' 'mysql' 'sys') )"
 	printf '\t%s\n' "-h,--help: Prints help"
 }
 
@@ -64,7 +67,7 @@ parse_commandline ()
 	do
 		_key="$1"
 		case "$_key" in
-			--username)
+			-u|--username)
 				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
 				_arg_username="$2"
 				shift
@@ -72,7 +75,10 @@ parse_commandline ()
 			--username=*)
 				_arg_username="${_key##--username=}"
 				;;
-			--password)
+			-u*)
+				_arg_username="${_key##-u}"
+				;;
+			-p|--password)
 				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
 				_arg_password="$2"
 				shift
@@ -80,7 +86,10 @@ parse_commandline ()
 			--password=*)
 				_arg_password="${_key##--password=}"
 				;;
-			--host)
+			-p*)
+				_arg_password="${_key##-p}"
+				;;
+			-H|--host)
 				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
 				_arg_host="$2"
 				shift
@@ -88,7 +97,10 @@ parse_commandline ()
 			--host=*)
 				_arg_host="${_key##--host=}"
 				;;
-			--port)
+			-H*)
+				_arg_host="${_key##-H}"
+				;;
+			-P|--port)
 				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
 				_arg_port="$2"
 				shift
@@ -96,7 +108,10 @@ parse_commandline ()
 			--port=*)
 				_arg_port="${_key##--port=}"
 				;;
-			--output-directory)
+			-P*)
+				_arg_port="${_key##-P}"
+				;;
+			-o|--output-directory)
 				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
 				_arg_output_directory="$2"
 				shift
@@ -104,17 +119,43 @@ parse_commandline ()
 			--output-directory=*)
 				_arg_output_directory="${_key##--output-directory=}"
 				;;
-			--no-gz|--gz)
-				_arg_gz="on"
-				test "${1:0:5}" = "--no-" && _arg_gz="off"
+			-o*)
+				_arg_output_directory="${_key##-o}"
 				;;
-			--ignore)
+			-c|--no-compress|--compress)
+				_arg_compress="on"
+				test "${1:0:5}" = "--no-" && _arg_compress="off"
+				;;
+			-c*)
+				_arg_compress="on"
+				_next="${_key##-c}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					begins_with_short_option "$_next" && shift && set -- "-c" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
+				;;
+			-q|--no-quiet|--quiet)
+				_arg_quiet="on"
+				test "${1:0:5}" = "--no-" && _arg_quiet="off"
+				;;
+			-q*)
+				_arg_quiet="on"
+				_next="${_key##-q}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					begins_with_short_option "$_next" && shift && set -- "-q" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
+				;;
+			-i|--ignore)
 				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
 				_arg_ignore+=("$2")
 				shift
 				;;
 			--ignore=*)
 				_arg_ignore+=("${_key##--ignore=}")
+				;;
+			-i*)
+				_arg_ignore+=("${_key##-i}")
 				;;
 			-h|--help)
 				print_help
@@ -169,15 +210,24 @@ exit_status=0
 for database in $databases; do
     dump_file=$_arg_output_directory"/"$database
     compressor=tee
-    if [[ $_arg_gz == "on" ]]; then
+    if [[ $_arg_compress == "on" ]]; then
        dump_file=${dump_file}.gz
        compressor=gzip
     fi
-    echo "Dumping database \`$database\` to '$dump_file'"
+
+    if [[ $_arg_quiet == "on" ]]; then
+        echo $database
+    else
+        echo "Dumping database \`$database\` to '$dump_file'"
+    fi
     mysqldump --host ${_arg_host} --opt -P ${_arg_port} -u ${_arg_username} -p${_arg_password} $database | ${compressor} > ${dump_file}
     if [ ${PIPESTATUS[0]} -ne "0" ];
     then
-        echoerr Backup Failed: $database
+        if [[ $_arg_quiet == "on" ]]; then
+            echoerr $database
+        else
+            echoerr Backup Failed: $database
+        fi
         exit_status=1
     fi
 done
